services:
  mongodb:
    container_name: "104-mongodb"
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - mongo_data:/data/db

  streamlit:
    build: .
    container_name: "streamlit"
    restart: always
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./104:/app/104
      - ./.env:/app/.env
      - ./cron/logs:/var/log/cron
    ports:
      - "8501:8501"
      - "8502:8502"
    depends_on:
      - mongodb

volumes:
  mongo_data:
