version: '3.8'

services:
  mongodb:
    container_name: "104-mongodb"
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: